name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run tests with coverage
      run: npm test -- --coverage

    - name: Fail if coverage < 80%
      run: |
        THRESHOLD=80
        COVERAGE=$(node -p "require('./coverage/coverage-summary.json').total.statements.pct")
        echo "Statements coverage: $COVERAGE%"
        if (( $(echo "$COVERAGE < $THRESHOLD" | bc -l) )); then
          echo "Coverage below $THRESHOLD%. Failing build."
          exit 1
        else
          echo "Coverage OK."
        fi